trigger:
  branches:
    include:
      - main

variables:
  nodeVersion: '18.x'

stages:
- stage: CI
  displayName: 'Continuous Integration'
  jobs:
  - job: BuildFrontend
    displayName: 'Build Frontend'
    pool:
      name: 'SelfHosted'
    
    steps:
    - task: NodeTool@0
      displayName: 'Setup Node.js'
      inputs:
        versionSpec: $(nodeVersion)
    
    - script: |
        npm ci
        npm run build
      displayName: 'Build Frontend'
      workingDirectory: '$(System.DefaultWorkingDirectory)/front'
    
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Frontend Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/front/build'
        artifact: 'frontend-dist'

  - job: BuildBackend
    displayName: 'Build Backend'
    pool:
      name: 'SelfHosted'
    
    steps:
    - task: NodeTool@0
      displayName: 'Setup Node.js'
      inputs:
        versionSpec: $(nodeVersion)
    
    - script: |
        npm ci
      displayName: 'Install Dependencies'
      workingDirectory: '$(System.DefaultWorkingDirectory)/back'
    
    - script: |
        npm run build || echo "No build script defined"
      displayName: 'Build Backend'
      workingDirectory: '$(System.DefaultWorkingDirectory)/back'
    
    - script: |
        npm test
      displayName: 'Test Backend'
      workingDirectory: '$(System.DefaultWorkingDirectory)/back'
      continueOnError: 'true'
    
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Backend Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/back'
        artifact: 'backend-dist'
